### ISSUE TITLE
Rhino Issue: No method RhinoInference

### ISSUE THREAD

**Issue by darys58** [Picovoice/rhino#550]
The application written in Flutter for Android behaves correctly on a smartphone connected to a computer in the development environment, but when downloaded to a smartphone from the Google Play store, it generates an error and closes the application. The error occurs after decoding the wake word, waiting for a command. It behaves as if the command was not received (although it was given) and instead of a message about not understanding the intention, the application is closed.
In the stack trace you can read: Abort message: 'art/runtime/thread.cc:1336] No pending exception expected: java.lang.NoSuchMethodError: no non-static method "Lai/picovoice/rhino/RhinoInference;<init>(ZLjava /lang/String;Ljava/until/Map;)V"

There is no such problem for iPhones.

**Comment by ErisMik** [comment]
@darys58 We've identified the issue and will be releasing a new version in the coming days. I will close this issue once the package is released.

**Comment by laves** [comment]
@darys58 - upgrade your `rhino_flutter` to [v2.2.2](https://pub.dev/packages/rhino_flutter/versions/2.2.2) and this should be resolved.

**Comment by darys58** [comment]
Upgrading rhino_flutter to v2.2.2 did not solve the problem (issue #550) -
still the application stops working as described earlier.
Same error occurs.
Additionally, version 2.2.2 generates an error for iOS:

CocoaPods could not find compatible versions for pod "ios-voice-processor":
In snapshot (Podfile.lock):
ios-voice-processor (= 1.0.3, ~> 1.0.2)
In Podfiles:
flutter_voice_processor (from
`.symlinks/plugins/flutter_voice_processor/ios`) was resolved to 1.1.0,
which depends on
ios-voice-processor (~> 1.1.0)

Running 'pod repo update', 'pod install' or 'pod update
ios-voice-processor' does not update the libraries due to incompatible
versions.
I still need to work on version 2.2.1

czw., 17 sie 2023 o 02:09 Ian Lavery ***@***.***> napisał(a):

**Comment by laves** [comment]
@darys58 - apologies, we missed updating a native package last release that would have solved your issue. The latest release [v2.2.3](https://pub.dev/packages/rhino_flutter/versions/2.2.3) should actually solve your issue in Android.

As for your issue with iOS, it looks as though you may just need to delete your `Podfile.lock` and run a new build. Your current lock file locks `ios-voice-processor` to 1.0.3, but the new flutter bindings will require 1.1.0.
